# This is what the knative service data source looks like
# I've included it here as a reference for what else needs to be added.

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    serving.knative.dev/creator: kubernetes-admin
    serving.knative.dev/lastModifier: kubernetes-admin
  creationTimestamp: "2023-06-11T02:31:14Z"
  generation: 1
  name: app
  namespace: default
  resourceVersion: "45415"
  uid: 8f708493-d8c4-4abc-8af0-93a5316fd32b
spec:
  template:
    metadata:
      annotations:
        client.knative.dev/updateTimestamp: "2023-06-11T02:31:14Z"
        client.knative.dev/user-image: ghcr.io/knative/helloworld-go
      creationTimestamp: null
    spec:
      containerConcurrency: 0
      containers:
      - image: ghcr.io/knative/helloworld-go
        name: user-container
        readinessProbe:
          successThreshold: 1
          tcpSocket:
            port: 0
        resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
status:
  address:
    url: http://app.default.svc.cluster.local
  conditions:
  - lastTransitionTime: "2023-06-11T02:31:17Z"
    status: "True"
    type: ConfigurationsReady
  - lastTransitionTime: "2023-06-11T02:31:17Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-06-11T02:31:17Z"
    status: "True"
    type: RoutesReady
  latestCreatedRevisionName: app-00001
  latestReadyRevisionName: app-00001
  observedGeneration: 1
  traffic:
  - latestRevision: true
    percent: 100
    revisionName: app-00001
  url: http://app.default.127.0.0.1.sslip.io
