name: Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: buildjet/setup-go@78375e30a2f771dcfd4af12334999a9ce35a95d1 # v4
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - run: go build -v .
      - name: Run linters
        uses: golangci/golangci-lint-action@639cd343e1d3b897ff35927a75193d57cfcba299 # v3.6.0
        with:
          version: latest

  test:
    name: Terraform Provider Acceptance Tests
    needs: build
    runs-on: buildjet-4vcpu-ubuntu-2204
    timeout-minutes: 5
    strategy:
      matrix:
        terraform:
          - '1.0.*'
          - '1.1.*'
          - '1.2.*'
          - '1.3.*'
          - '1.4.*'
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: buildjet/setup-go@78375e30a2f771dcfd4af12334999a9ce35a95d1 # v4
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - run: go mod download
      - name: kn quickstart kind --install-serving
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.19.0/kind-linux-amd64
          chmod +x ./kind
          mv ./kind /usr/local/bin/kind
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          mv ./kubectl /usr/local/bin/kubectl
          wget https://github.com/knative/client/releases/download/knative-v1.10.0/kn-linux-amd64
          chmod +x ./kn-linux-amd64
          mv ./kn-linux-amd64 /usr/local/bin/kn
          curl -Lo ./quickstart https://github.com/knative-sandbox/kn-plugin-quickstart/releases/download/knative-v1.10.0/kn-quickstart-linux-amd64
          chmod +x ./quickstart
          ./quickstart kind --install-serving
      - env:
          TF_ACC: "1"
        run: |
          kubectl create namespace example
          kn service create app --namespace=example --image ghcr.io/knative/helloworld-go
          go test -v -cover ./internal/provider/

  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: buildjet/setup-go@78375e30a2f771dcfd4af12334999a9ce35a95d1 # v4
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go generate ./...
      - name: git diff
        run: |
          git diff --compact-summary --exit-code || \
            (echo echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit." exit 1)
